
version: 2

models:
  - name: fct_games
    sources:
      - name: raw_events  # Logical name for the source
        database: playperfect-451608  # Your BigQuery project ID
        schema: play_perfect_dataset
        tables:
          - name: pp_events  # Your source table
